SIM ?= icarus
TOPLEVEL_LANG ?= verilog

VERILOG_SOURCES += $(PWD)/../rtl/ca_cell.v
VERILOG_SOURCES += $(PWD)/../rtl/ca_grid.v
VERILOG_SOURCES += $(PWD)/../rtl/uart_tx.v
VERILOG_SOURCES += $(PWD)/../rtl/grid_streamer.v
VERILOG_SOURCES += $(PWD)/../rtl/cellnet_top.v
TOPLEVEL = cellnet_top
MODULE = test_cellnet_top
COMPILE_ARGS += -Pcellnet_top.CLKS_PER_BIT=4

include $(shell cocotb-config --makefiles)/Makefile.sim
